swagger: '2.0'
info:
  title: Example yaml.spec1
  description: 
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><img onerror=alert('123456') src=1 /><textarea></textarea>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
